/**
 * Typed access to the balance tables extracted from the legacy PHP.
 * The .json files here are generated by tools/extract-gamedata.py and verified
 * against fixtures/lookups.json by tools/verify-gamedata.py -- do not edit them
 * by hand.
 */

import buildingsJson from './buildings.json' with { type: 'json' }
import curvesJson from './curves.json' with { type: 'json' }
import enJson from './i18n/en.json' with { type: 'json' }
import trJson from './i18n/tr.json' with { type: 'json' }
import islandJson from './island.json' with { type: 'json' }
import pediaJson from './pedia.json' with { type: 'json' }
import islandsSeedJson from './islands.seed.json' with { type: 'json' }
import mapsJson from './maps.json' with { type: 'json' }
import researchJson from './research.json' with { type: 'json' }
import templeJson from './temple.json' with { type: 'json' }
import unitsJson from './units.json' with { type: 'json' }

export interface UnitStats {
  peoples: number
  wood: number
  sulfur: number
  wine: number
  crystal: number
  gold: number
  time: number
  defence: number
  health: number
  class: number
  speed: number
  ability: number
  capacity: number
}

export interface LevelTable {
  max_level: number
  /** Sparse: a building only lists the resources it actually costs. */
  levels: Partial<Record<'wood' | 'wine' | 'marble' | 'crystal' | 'sulfur' | 'time', number[]>>
}

export interface IslandTable {
  max_level: number
  /** island_cost() indexes with (level - 1). */
  level_offset: number
  levels: Partial<Record<'wood' | 'workers' | 'time', number[]>>
}

export interface ResearchNode {
  way: number
  id: number
  points: number
  /** Ordered alternatives: the first unmet one is reported as the blocker. */
  requires: { way: number; id: number }[]
  name_key: string
  desc_key: string
}

export interface IslandSeed {
  id: number
  name: string
  x: number
  y: number
  type: number
  trade_resource: number
  wonder: number
  [k: string]: number | string
}

export const UNITS = unitsJson as unknown as Record<string, UnitStats>

/**
 * The temple, which no extractor can produce: `building_cost()` in the legacy
 * has no `case 26`, so a temple there costs nothing and stops at level 0.
 *
 * These are live Ikariam's tables, transcribed by hand -- wood and marble per
 * level, the build time in seconds, the priests a temple of that level houses,
 * and the wonder's own expansion cost. Levels 1-40 (wood 1-49) are the
 * published figures verbatim; the last few marble entries and wood level 50
 * are printed abbreviated in the source ("1,09M"), so they are completed from
 * the observed ratio decay `r(n+1) = 1 + (r(n) - 1) * 0.997`, which lands
 * inside 0.3% of every abbreviated figure. Replace them if exact ones surface.
 *
 * It lives in its own file because `buildings.json` is generated by
 * tools/extract-gamedata.py and verified against fixtures/lookups.json; a hand
 * written entry in there would be overwritten by the next extraction.
 */
export const TEMPLE = templeJson as unknown as {
  building: LevelTable
  /** Indexed by temple level; index 0 is the missing temple. */
  priests: number[]
  /**
   * The monument's own expansion. `cost_per_good[n]` is what EACH of the three
   * donatable luxuries costs to reach level n+1, indexed by the current level.
   */
  wonder: { max_level: number; cost_per_good: number[] }
}

export const BUILDINGS = {
  ...(buildingsJson as unknown as Record<string, LevelTable>),
  '26': TEMPLE.building,
} as Record<string, LevelTable>
export const ISLAND_NODES = islandJson as unknown as Record<string, IslandTable>
export const RESEARCH = researchJson as unknown as {
  repeat_multiplier: string
  nodes: Record<string, ResearchNode>
}
export const CURVES = curvesJson as unknown as Record<string, Record<string, number>>
export const MAPS = mapsJson as unknown as Record<string, Record<string, string | number>>
export const ISLANDS_SEED = islandsSeedJson as unknown as IslandSeed[]

/**
 * The English language file, 1,466 keys, lifted from
 * izariam/language/english/site_lang.php. Nearly every string the screens
 * render comes from here rather than from the markup -- the 1,622-line
 * pedia/informations pair is driven entirely off 721 of these keys.
 */
export const EN = enJson as unknown as Record<string, string>

/**
 * The Turkish translation, hand-written against the same 1,466 keys as EN.
 * Missing keys fall back to EN at the lookup site (apps/web/src/lib/i18n.ts).
 */
export const TR = trJson as unknown as Record<string, string>

/** One block of an encyclopedia topic: a caption to look up, or an image. */
export type PediaBlock =
  | { kind: 'title' | 'heading' | 'text'; key: string }
  | { kind: 'image'; src: string }

/**
 * The encyclopedia, extracted from the two 811-line PHP files by
 * tools/extract-pedia.py. Both are the same body -- a title, then headings,
 * paragraphs and pictures -- with different topic numbers, so only the order
 * of language keys is worth keeping.
 */
export const PEDIA = pediaJson as unknown as {
  pedia: Record<string, PediaBlock[]>
  informations: Record<string, PediaBlock[]>
}

/** Unit ids are 1-based. */
export const UNIT_IDS = Object.keys(UNITS).map(Number).sort((a, b) => a - b)

/** Research branch -> node count, as enforced by get_research()'s clamps. */
export const RESEARCH_BRANCH_SIZE: Record<number, number> = { 1: 14, 2: 15, 3: 16, 4: 14 }

/** Building type -> css class name, straight from building_class_by_type(). */
export const BUILDING_CLASS = MAPS.building_class_by_type as Record<string, string>

/** Island trade_resource -> resource column name. */
export const RESOURCE_CLASS = MAPS.resource_class_by_type as Record<string, string>
